CSHSoft/Areas/Admin/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CSHFSoft.AccesoDatos.Data.Repository;
using CSHSoft.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CSHSoft.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]

    public class UsuariosController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public UsuariosController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var usuarioActual = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return View(_contenedorTrabajo.Usuario.GetAll(u => u.Id != usuarioActual.Value));
        }
        public IActionResult Bloquear(string id, Auditoria auditoria)
        {
            if (id == null)
            {
                return NotFound();

            }

            _contenedorTrabajo.Usuario.BloqueaUsuario(id);
            _contenedorTrabajo.Auditoria.Add(auditoria);
            auditoria.nombreUsuario = @User.Identity.Name;
            auditoria.fecha = DateTime.Now;
            auditoria.accion = "Bloqueo usuario con id " + id;
            _contenedorTrabajo.Save();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Desbloquear(string id, Auditoria auditoria)
        {
            if (id == null)
            {
                return NotFound();

            }

            _contenedorTrabajo.Usuario.DesbloquearUsuario(id);
            _contenedorTrabajo.Auditoria.Add(auditoria);
            auditoria.nombreUsuario = @User.Identity.Name;
            auditoria.fecha = DateTime.Now;
            auditoria.accion = "Desbloqueo usuario con id " + id;
            _contenedorTrabajo.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

CSHSoft/Areas/Admin/Controllers/VeterinariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CSHFSoft.AccesoDatos.Data.Repository;
using CSHSoft.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CSHSoft.Areas.Admin.Controllers

{   [Authorize] 
    [Area("Admin")]
    public class VeterinariosController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
     

        public VeterinariosController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet] //Llamada al formulario Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Veterinario veterinario, Auditoria auditoria)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Veterinario.Add(veterinario);
                _contenedorTrabajo.Save();
                auditoria.nombreUsuario = @User.Identity.Name;
                auditoria.fecha = DateTime.Now;
                auditoria.accion = "Alta Veterinario";
                _contenedorTrabajo.Auditoria.Add(auditoria);
                _contenedorTrabajo.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(veterinario);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Veterinario veterinario = new Veterinario();
            veterinario = _contenedorTrabajo.Veterinario.Get(id);
            if (veterinario == null)
            {
                return NotFound();
            }

            return View(veterinario);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(Veterinario veterinario, Auditoria auditoria)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Veterinario.Update(veterinario);
                auditoria.nombreUsuario = @User.Identity.Name;
                auditoria.fecha = DateTime.Now;
                auditoria.accion = "Edicion Veterinario";
                _contenedorTrabajo.Auditoria.Add(auditoria);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(veterinario);
        }

        #region LLAMADAS A LA API
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { Data = _contenedorTrabajo.Veterinario.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id, Auditoria auditoria)
        {
            var objeto = _contenedorTrabajo.Veterinario.Get(id);
            if (objeto == null)
            {
                return Json(new { success = false, message = "Error" });
            }

            _contenedorTrabajo.Veterinario.Remove(objeto);
            _contenedorTrabajo.Auditoria.Add(auditoria);
            auditoria.nombreUsuario = @User.Identity.Name;
            auditoria.fecha = DateTime.Now;
            auditoria.accion = "Eliminado Veterinario";
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Veterinario Eliminado correctamente" });
        }
        #endregion
    }
}

CSHSoft/Views/Shared/_Layout.cshtml
@using CSHSoft.Utilidades
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CSHSoft</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="Cliente" asp-controller="Home" asp-action="Index">CSH web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav mr-auto">
                        @if (User.IsInRole(Roles.Admin))
                        {


                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle text-white" id="navbarDropDrown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Contenidos
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropDrown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Veterinarios" asp-action="Index">Veterinarios</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                            </div>
                        </li>
                        }
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CSHSoft - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/0a1be2cb69.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CSHSoft/Views/Shared/_VistaCrearVolver.cshtml
<div class="row">
    <div class="col" style="margin-top: 10px;">
        <a asp-action="Index" class="btn btn-success form-control" style="width:max-content;">Volver</a>
    </div>
    <div class="col" style="margin-top: 10px;">
        <button type="submit" class="btn btn-primary form-control" style="width:max-content;">Agregar</button>
        &nbsp;
    </div>    
</div>